codigo
bitfocus/companion-module-monteiro-pptvideoosc pull request #1
Opened 2024-05-26 18:23 UTC by MonteiroVideo

2024-05-26 19:14 UTC, dnmeid requested changes
At this stage this module is just a prefilled generic OSC sender. It provides only a tiny advantage over the generic OSC module.
I still don't see how your software does provide any advantage over the existing PPT control plugins. They do have a lot more features and useful feedback. But that is your decision. From my side the code needs to be error free and the module should be usable for the average user and at the moment it is simply bad design.

2024-05-26 19:14 UTC, dnmeid commented on main.js
> +							value: parseInt(int),
What happens when the user enters `-149588357.2`? Or `this is not a number`? Regex on option does not validate input, it just gives a visual hint.

2024-05-26 19:14 UTC, dnmeid commented on main.js
> +				name: 'Anterior',
All the same as above

2024-05-26 19:14 UTC, dnmeid commented on main.js
> +			send_prox: {
Again all the same as above

2024-05-26 19:14 UTC, dnmeid commented on main.js
> +			send_exit: {
And again

2024-05-26 19:14 UTC, dnmeid commented on main.js
> +			send_exitV: {
And again again

2024-05-26 19:14 UTC, dnmeid commented on main.js
> +			send_video1: {
History repeating, I hope you got the point.

2024-05-26 19:14 UTC, dnmeid commented on presets.js
Please also use english for presets

2024-06-01 11:43 UTC, MonteiroVideo commented
ITS OK

2024-06-01 12:47 UTC, dnmeid requested changes
It's not ok

2024-06-01 12:47 UTC, dnmeid commented on companion/manifest.json
> +	"description": "Perform operations on separate machines.",
Please use a more precise and descriptive description. "operations" can be anything, "machines" can be anything

2024-06-01 12:47 UTC, dnmeid commented on companion/manifest.json
> +	"shortname": "monteiro-pptvideoosc",
the shortname is the same as the name. it should be shorter, just the minimum to recognize the connection

2024-06-01 12:47 UTC, dnmeid commented on companion/manifest.json
> +	"keywords": [POWERPOINT, VIDEO, TIMER]
There is no timer related handling in the module, this is a misleading keyword.

2024-06-01 12:47 UTC, dnmeid commented on companion/HELP.md
> +All the presets are done, but if you have any questions, send me a message on Instagram. Monteiro.audiovisual
The help file should give help about the module, the configuration, the actions, the feedbacks and so on. If I read this, I get no help. And I have questions: what is this connection for? I can't see its purpose.

2024-06-01 12:47 UTC, dnmeid commented on main.js
> +		for (let i = 1; i <= 20; i++) {
You still completely don't understand, what you are doing wrong and I really don't know how I can explain it in even more detail.
1. Do not make 20 different actions if there is only one parameter changing. Instead make this _**one**_ action where the changing parameter is an _**option**_.
2. There is completely no use in your 'COMANDO' in beinig a user editable textinput. Actually this makes all your actions the same action.

2024-06-01 12:47 UTC, dnmeid commented on main.js
> +						default: 1,
Default value for a textinput needs to be a string

2024-06-01 12:47 UTC, dnmeid commented on main.js
> +		actionDefinitions[`send_int`] = {
This is still copy/paste from the OSC module

2024-06-01 12:47 UTC, dnmeid commented on main.js
> +		for (let i = 1; i <= 10; i++) {
Same as above

2024-06-01 12:47 UTC, dnmeid commented on main.js
> +						label: 'COMANDO',
Good use of forEach here, but the 'COMANDO' option should not be present at all, it is not needed.

2024-06-01 12:47 UTC, dnmeid commented on package.json
> +		"url": "git+https://github.com/MonteiroVideo/companion-module-monteiro-pptvideoosc.git"
Update url

2024-06-01 12:47 UTC, dnmeid commented on presets.js
> +                            actionId: 'send_int',
You are using the generic send_int action, where you have a dedicated action

2024-06-01 12:47 UTC, dnmeid commented on presets.js
> +                        actionId: 'send_int',
You are using the generic send_int action for a process, which doesn't need an integer at all and which should have its own action.

2024-06-01 12:47 UTC, dnmeid commented on presets.js
> +            name: 'pr_init',
All your presets have the same meaningless name.

2024-06-01 12:47 UTC, dnmeid commented on presets.js
> +                        actionId: 'send_int',
same send_int

2024-06-01 12:47 UTC, dnmeid commented on presets.js
> +                        actionId: 'send_int',
again

2024-06-01 12:47 UTC, dnmeid commented on presets.js
> +                        actionId: 'send_int',
again

2024-06-01 12:47 UTC, dnmeid commented on presets.js
> +                        actionId: 'send_int',
again

2024-06-06 23:03 UTC, closed without merging